"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.sendTokens = exports.sendAda = exports.getWalletInfo = exports.registerCardanoTools = exports.registerBitcoinCashTools = exports.registerDogecoinTools = exports.registerLitecoinTools = exports.registerBitcoinTools = void 0;
var bitcoin_js_1 = require("./bitcoin.js");
Object.defineProperty(exports, "registerBitcoinTools", { enumerable: true, get: function () { return bitcoin_js_1.registerBitcoinTools; } });
var litecoin_js_1 = require("./litecoin.js");
Object.defineProperty(exports, "registerLitecoinTools", { enumerable: true, get: function () { return litecoin_js_1.registerLitecoinTools; } });
var dogecoin_js_1 = require("./dogecoin.js");
Object.defineProperty(exports, "registerDogecoinTools", { enumerable: true, get: function () { return dogecoin_js_1.registerDogecoinTools; } });
var bitcoincash_js_1 = require("./bitcoincash.js");
Object.defineProperty(exports, "registerBitcoinCashTools", { enumerable: true, get: function () { return bitcoincash_js_1.registerBitcoinCashTools; } });
var cardano_js_1 = require("./cardano.js");
Object.defineProperty(exports, "registerCardanoTools", { enumerable: true, get: function () { return cardano_js_1.registerCardanoTools; } });
Object.defineProperty(exports, "getWalletInfo", { enumerable: true, get: function () { return cardano_js_1.getWalletInfo; } });
Object.defineProperty(exports, "sendAda", { enumerable: true, get: function () { return cardano_js_1.sendAda; } });
Object.defineProperty(exports, "sendTokens", { enumerable: true, get: function () { return cardano_js_1.sendTokens; } });
